

USE ContosoRetailDW;

WITH ANALISE_PRODUTO(ANO, MES, ID_PRODUTO, NOME_PRODUTO, QUANTIDADE)
AS
(
	SELECT
		DATEPART(YEAR, S.DateKey) AS ANO,
		DATEPART(MONTH, S.DateKey) AS MES,
		S.ProductKey AS ID_PRODUTO,
		P.ProductName AS NOME_PRODUTO,
		SUM(S.SalesQuantity) AS QUANTIDADE 
	FROM FactSales S
	INNER JOIN DimProduct P ON P.ProductKey = S.ProductKey
	GROUP BY DATEPART(YEAR, S.DateKey), DATEPART(MONTH, S.DateKey), S.ProductKey, P.ProductName
)
SELECT
	*
FROM ANALISE_PRODUTO
ORDER BY QUANTIDADE DESC