


USE ContosoRetailDW

SELECT TOP 100
	S.DateKey,
	DATENAME(DAY, S.DateKey) AS DIA_DA_SEMANA,
	DATENAME(WEEKDAY, S.DateKey) AS NOME_DIA_DA_SEMANA,
	DATENAME(MONTH, S.DateKey) AS NOME_MES_DA_SEMANA
FROM FactOnlineSales S
ORDER BY S.DateKey DESC